# 회원 가입
POST {{host}}/auth/signup
Content-Type: application/json

{
  "email": "jungmini0601@gmail.com",
  "password": "qwer1234",
  "nickname": "jungmini",
  "userRole": "ROLE_ADMIN"
}

###

# 로그인
POST {{host}}/auth/signin
Content-Type: application/json

{
  "email": "jungmini0601@gmail.com",
  "password": "qwer12344"
}