# 투두 생성
POST {{host}}/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJqdW5nbWluaTA2MDFAZ21haWwuY29tIiwibmlja25hbWUiOiJqdW5nbWluaSIsInVzZXJSb2xlIjoiQURNSU4iLCJleHAiOjE3NDY5MTkyOTEsImlhdCI6MTc0NjkxNTY5MX0.P-oAGPAejoK0nyEVe6JjXCu2Y_j823Wi4EIkjUrsGwk

{
  "title": "test title",
  "contents": "test contents"
}