# 투두 생성
POST {{host}}/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJqdW5nbWluaTA2MDFAZ21haWwuY29tIiwibmlja25hbWUiOiJqdW5nbWluaSIsInVzZXJSb2xlIjoiQURNSU4iLCJleHAiOjE3NDY5MzA2MTksImlhdCI6MTc0NjkyNzAxOX0.DHn-AMKOfPRg10xp9g-xPSIW1d6MH-g6p6VpEH8OR4o

{
  "title": "test title",
  "contents": "test contents"
}
###

# 투두 조회
GET {{host}}/todos?weather=d
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJqdW5nbWluaTA2MDFAZ21haWwuY29tIiwibmlja25hbWUiOiJqdW5nbWluaSIsInVzZXJSb2xlIjoiQURNSU4iLCJleHAiOjE3NDY5MjEwMTEsImlhdCI6MTc0NjkxNzQxMX0.FzbieIXx-avK--M8KPMQ-ewG7LZjXKyhrRv7eejab3c